spring.application.name=fartmeter

# PostgreSQL (default)
spring.datasource.url=${POSTGRES_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PWD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
